### ISSUE TITLE
Installed but not?

### ISSUE THREAD

**Issue by HullaBrian** [heywoodlh/urlscan-py#11]
I installed the code via pip3 with the command: pip3 install —user urlscan-py. This command worked and the installation was successful, however once I started to attempt to use the code, I would get error messages saying that URL’s an is not a command.

**Comment by heywoodlh** [comment]
It's most likely a $PATH issue. Are you on Windows, Mac, Linux, BSD? 

On Linux and MacOS, I believe the default `$PATH` for `pip3` installed binaries is `~/.local/bin`. So you'd have to add `~/.local/bin/` to your $PATH, or just invoke the full path to the executable, like so:

```bash
~/.local/bin/urlscan --help
```


Hope that helps.

**Comment by heywoodlh** [comment]
If you are on MacOS/Linux, you can install `urlscan` globally with `sudo`:

```bash
sudo pip3 install urlscan-py
```

That will place it in a location that every user on the machine will be able to see.

**Comment by HullaBrian** [comment]
That fixed my issue. Thank you so much!
