### ISSUE TITLE
UUID retrieval

### ISSUE THREAD

**Issue by HullaBrian** [heywoodlh/urlscan-py#12]
I ran a scan and attempted to save the uuid to a database file. 1. I have no clue how to access the file or use the values in the program, 2. The scan just idles forever(As far as I can tell) So there is no way of knowing if it works or not.

**Comment by HullaBrian** [comment]
All that I am after here is an easy way to get the uuid and use that to retrieve a screenshot.

**Comment by HullaBrian** [comment]
I tried using this:

> `python urlscan.py scan -f urls.txt >> saved_scans.txt`

This raises the error:
>  python: can’t open file ‘urlscan.py’: [Errno 2] No such file or directory

**Comment by heywoodlh** [comment]
In regard to your last error, `python: can’t open file ‘urlscan.py’: [Errno 2] No such file or directory`, that is due to there not being a file in this repository named `urlscan.py`. You should install urlscan-py via pip:

```bash
pip3 install urlscan-py
```


To your other issue, there should be a confirmation message when your scan is submitted, so you _should_ be notified if `urlscan` submits a url to be scanned. For example:

```bash
$ urlscan scan -f scanurls.txt
{
  "message": "Submission successful",
  "uuid": "462b47af-b0aa-4622-ba31-ad0070177530",
  "result": "https://urlscan.io/result/462b47af-b0aa-4622-ba31-ad0070177530/",
  "api": "https://urlscan.io/api/v1/result/462b47af-b0aa-4622-ba31-ad0070177530/",
  "visibility": "private",
  "options": {
    "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
  },
  "url": "https://the-empire.systems"
}
{
  "message": "Submission successful",
  "uuid": "13ce799f-02c9-4a24-af59-99f87e701856",
  "result": "https://urlscan.io/result/13ce799f-02c9-4a24-af59-99f87e701856/",
  "api": "https://urlscan.io/api/v1/result/13ce799f-02c9-4a24-af59-99f87e701856/",
  "visibility": "private",
  "options": {
    "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
  },
  "url": "https://example.com"
}
```

To your first point, there is an a way to invoke `urlscan` to retrieve saved UUIDs in the database, so you don't have to worry about interfacing with the database directly.

That being said, I only designed it initially to search for specific URLs, for example:

```bash
$ urlscan search --url https://the-empire.systems
('https://the-empire.systems', '74234b5c-2002-4796-b531-26ceec8338fc', '2020-04-11 16:48:19')
```

I will add a new flag to the search parser to allow you to see all URLs. I will let you know when I commit the change to the code.

**Comment by HullaBrian** [comment]
That helps a lot however, it seems that when the search command runs, you cannot harness the output. Here is what I have:
`for x in range(0, LineListLen):
       outlist = os.system("urlscan search --url {}".format(LineList[x]))
       x += 1
print(outlist)`
This returns the following:
`('https://urlscan.io', '92f0fd9a-4199-4683-b764-b215faf18dea', '2020-04-10 18:56:51')
0`
So I guess what is happening is that I cannot assign the returned seach value to a variable so that I can use the UUID. What I was aiming for was automated result saving. However, it appears that I will have to manually put in the UUID. 
That being said, addressing what you said, "To your first point, there is an a way to invoke urlscan to retrieve saved UUIDs in the database, so you don't have to worry about interfacing with the database directly." How so? I cannot seem to prompt the urlscan to retrive any saved UUIDs.

**Comment by heywoodlh** [comment]
So I plan to implement `urlscan-py` as a Python library at some point. I haven't yet, though. Once I do this, it'll make using the same functions in urlscan-py in your/other Python projects much easier. 

I have made a few updates (make sure to `pip3 install urlscan-py==1.1.2` to upgrade to the latest version), so per [this commit](eefee391a8e0b) you can now use the `all` value for the `--url` argument. This will return every saved scan in the database. Notice that the output format is a bit different (I tried to make it look a little cleaner vs the default Python Tuple look):

```bash
$ ./urlscan search --url all
2020-04-11 16:48:19 || https://the-empire.systems: 74234b5c-2002-4796-b531-26ceec8338fc
```

With this new format you could do something like this `awk` to retrieve only the UUIDs:

```bash
urlscan search --url all | awk '{print $5}'
```

It returns just the UUID:

```bash
$ urlscan search --url all | awk '{print $5}'
74234b5c-2002-4796-b531-26ceec8338fc
```

Here is a simple Python approach I threw together using the `subprocess` module and the above method:

```
>>> uuidList = subprocess.check_output("urlscan search --url all | awk '{print $5}'", shell=True)


>>> print(uuidList.decode('utf-8'))

74234b5c-2002-4796-b531-26ceec8338fc
```


Hopefully the examples help. Feel free to close the issue if this resolves your problem :)

If I don't hear back, I will leave this open for a few days and then close.

**Comment by HullaBrian** [comment]
I put in exactly what you said to do:
`uuidList = subprocess.check_output(“urlscan search —url all | awk ‘{print $5}’, shell=True)
print(uuidList.decode(‘utf-8’))`
Before this code, a scan on a site ran. After that, this code ran and produced a blank space. So I think what is going on is that the .db file has no scans in it.            So when a scan happens, doesn’t the information go into the database file?

**Comment by heywoodlh** [comment]
Yes, how are you triggering a scan?

-------- Original Message --------

**Comment by HullaBrian** [comment]
My initial scan is:
`scan = str(os.system(“urlscan scan —url * —file FILE.txt —dB urlscan.db”))`

**Comment by HullaBrian** [comment]
The initial scan is:
`scan = str(os.system("urlscan scan --url * --file PhishList.txt --db urlscan.db"))
`
Here is the code so far:
`import os
import subprocess

scan = str(os.system("urlscan scan --url * --file PhishList.txt --db urlscan.db"))

uuidList = subprocess.check_output("urlscan search --url all | awk '{print $5}'", shell=True)
print(uuidList.decode('utf-8'))
` 
Right now, the code just idles forever.

Edit: Could it have something to do with converting the output into a string? I don’t think that conversion is necessary.

**Comment by HullaBrian** [comment]
I actually figured it out:
`url_scan = subprocess.run(["urlscan", "scan", "--url", "*","--file",""PhishList.txt"], text=True, capture_output=True)
output = url_scan.stdout
print(output)

output_lst = output.split("\n")
uuid = output_lst[2]
uuid = uuid[11:-2]
print(uuid)`
