### ISSUE TITLE
Rate-limit support

### ISSUE THREAD

**Issue by SyeedHasan** [heywoodlh/urlscan-py#14]
Script crashes rather than either going to sleep or switching modes to public/private for a retry (after consent). 

`
Traceback (most recent call last):
  File "/home/K/.local/bin/urlscan", line 384, in <module>
    main()
  File "/home/K/.local/bin/urlscan", line 372, in main
    submit(args.url, urlscan_api, args.file, args.db, args.public, args.quiet)
  File "/home/K/.local/bin/urlscan", line 142, in submit
    save_history(target_url, r)
  File "/home/K/.local/bin/urlscan", line 339, in save_history
    result = result.split(":",1)[1]
IndexError: list index out of range
`

Do you accept PRs if this is worth a look? Do let me know if I've messed something up in understanding the code (and there is support for it).

**Comment by heywoodlh** [comment]
Sure thing, feel free to make a PR for this. I haven't ever hit the rate-limit so I haven't actually messed with any of the rate-limit behavior. My use of urlscan-py is checking URLs every so often -- maybe like once a month.

If you make a PR to more gracefully deal with the rate-limiting I would be very grateful. 🙏

**Comment by SyeedHasan** [comment]
Awesome. I'll add it to my list and get to work soon ;)

**Comment by heywoodlh** [comment]
Thanks for the pull request @SyeedHasan! I got it merged after I made some very minor wording changes:

c8d31738aa995eba1dec16649622123993a6b0e8
