### ISSUE TITLE
Not handling \\(

### ISSUE THREAD

**Issue by deepvoice** [heywoodlh/urlscan-py#17]
urlscan scan --url https://example.com/Local%20test**\\(**does%20not%20work

-bash: syntax error near unexpected token `('

**Comment by heywoodlh** [comment]
This is not an issue with urlscan-py this is an issue with BASH and escaping things properly. 

I was able to scan the URL just fine once I placed it in single quotes:

![image](https://user-images.githubusercontent.com/18178614/156301482-61bd360b-0fb4-4c07-abcd-52a63fd77005.jpeg)

**Comment by heywoodlh** [comment]
Let me know if your problem isn't resolved -- I'm closing this in the meantime.
