### ISSUE TITLE
Feature Request - Retry on Retrieve

### ISSUE THREAD

**Issue by deepvoice** [heywoodlh/urlscan-py#18]
Feature Request 
add retry count and delay (in seconds) options to urlscan retrieve

Example:
urlscan retrieve --uuid blah --retry 3 --retry_delay 30

urlscan will return a non-zero status error if trying to retrieve too soon before it's rendered at urlscan.io.

**Comment by heywoodlh** [comment]
So I am totally open to feedback on this, but I actually think this should be handled by however you are calling the tool.

When I try to retrieve a scan for a UUID that doesn't exist or hasn't completed, urlscan will return an error code 5:

![image](https://user-images.githubusercontent.com/18178614/159636086-32c5b262-12a0-4f3f-8f81-9cedcbd06819.jpeg)


If I were using a shell script, I could easily check for error code 5 and then add some logic to retry three or more times if that happens.

My preference would be to not add a retry flag in favor of a shell script or some other external program doing the checking.

Please let me know what you think.

**Comment by heywoodlh** [comment]
Closing due to lack of response.
