### ISSUE TITLE
Possible to Add feature public scans?

### ISSUE THREAD

**Issue by Hestat** [heywoodlh/urlscan-py#4]
So currently the scanner sends all requests as private scans, might there be a good way to allow the private/public to be a configurable option?

**Comment by heywoodlh** [comment]
Hey @Hestat thanks for reaching out. Per your request, this feature has now been added.

Upgrade to the newest version of `urlscan-py`:
`pip3 install urlscan-py=='1.0.1'`

All you have to do is when you submit a scan include the `--public` argument to submit it as a public scan. Here is an example:

`urlscan scan --url https://www.the-empire.systems --public`

The output from the API is as follows:

```
(urlscan-py)❯ urlscan scan --url https://www.the-empire.systems --public
{
  "message": "Submission successful",
  "uuid": "<omitted>",
  "result": "https://urlscan.io/result/<omitted>/",
  "api": "https://urlscan.io/api/v1/result/<omitted>/",
  "visibility": "public",
  "options": {
    "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.
0.3396.87 Safari/537.36"
  },
  "url": "https://www.the-empire.systems"
}
```



Please let me know if you have any issues with this. I will be closing the issue now but feel free to open it again if there are any problems.
