### ISSUE TITLE
Searching via API

### ISSUE THREAD

**Issue by jaredscottwilson** [heywoodlh/urlscan-py#6]
Is there any plan of implementing more search functionality rather just scan and scan retrieval?

**Comment by heywoodlh** [comment]
There wasn't a plan to do this until you mentioned it! :) 

I have just now added the functionality as part of the `search` subcommand using the `--web` argument (along with some other improvements to the code). 

Here is an example:

`urlscan scan --url google.com --public`
`urlscan search --url google.com --web`

With the way I have implemented it if the `--web` argument is called `search` will just search urlscan.io's API (not the local database) for any URL's that match that have had a public search performed on them previously.

Upgrade to the newest version:

`pip3 install --user urlscan-py==1.0.2`

Let me know if that works.

**Comment by heywoodlh** [comment]
Going to close this as I haven't heard anything
